version: "2"

services:
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: demo-rental

    # volumes:
    #   - ./init-seed-data/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    #   - ./db:/data/db
    restart: always
    networks:
      - default

volumes:
  mongo_data:
    driver: local